PracaMgr/urls.py
from django.conf.urls import url
from django.contrib import admin
import django.contrib.auth.views
from app import views, forms

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),

    url(r'^semesters/$', views.semesters, name='semesters'),
    url(r'^semesters/properties/$', views.semester_properties, name='semester_properties'),
    url(r'^semesters/create/$', views.create_semester, name='create_semester'),

    url(r'^students/$', views.students, name='students'),
    url(r'^students/details/$', views.student_details, name='student_details'),
    url(r'^students/create/$', views.create_student, name='create_student'),

    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login/login.html',
            'authentication_form': forms.CustomAuthenticationForm,
            'extra_context':
            {
                'title': 'Logowanie',
            }
        },
        name='login'),
    url(r'^logout/$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/home/',
        },
        name='logout'),

    url(r'^admin/', admin.site.urls),
]

app/models.py
from django.db import models

WYKLAD = 'WYK'
CWICZENIA = 'CW'
LABORATORIUM = 'LAB'
PROJEKT = 'PR'
SEMINARIUM = 'SEM'
CLASSES_CHOICES = (
    (WYKLAD, 'Wykład'),
    (CWICZENIA, 'Ćwiczenia'),
    (LABORATORIUM, 'Laboratorium'),
    (PROJEKT, 'Projekt'),
    (SEMINARIUM, 'Seminarium dyplomowe'),
)

LETNI = 'l'
ZIMOWY = 'z'
SEM_CHOICES = (
    (LETNI, 'letni'),
    (ZIMOWY, 'zimowy'),
)


class Semester(models.Model):
    name = models.CharField(max_length=8, unique=True)
    sem_type = models.CharField(max_length=1, choices=SEM_CHOICES, default=ZIMOWY)
    start_date = models.DateField()
    end_date = models.DateField()
    active = models.BooleanField(default=True)


class Student(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)


class Group(models.Model):
    name = models.CharField(max_length=50)
    group_type = models.CharField(max_length=3, choices=CLASSES_CHOICES, default=WYKLAD)
    students = models.ManyToManyField(Student)


class Subject(models.Model):
    name = models.CharField(max_length=100)


class Classes(models.Model):
    class_type = models.CharField(max_length=3, choices=CLASSES_CHOICES, default=WYKLAD)
    subject = models.ForeignKey(Subject)
    group = models.ForeignKey(Group)

app/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _


class CustomAuthenticationForm(AuthenticationForm):
    """Authentication form."""
    username = forms.CharField(max_length=254, label="Nazwa użytkownika",
                               widget=forms.TextInput({
                                   'placeholder': 'Wpisz nazwę użytkownika'}))
    password = forms.CharField(label="Hasło",
                               widget=forms.PasswordInput({
                                   'placeholder':'Wpis hasło'}))


class SemesterForm(forms.Form):
    academic_year = forms.CharField(max_length=7)
    sem_type = forms.ChoiceField(choices=[('z','zimowy'), ('l','letni')], widget=forms.RadioSelect)
    start_date = forms.DateField(input_formats=[
        '%d.%m.%Y',       # '25.10.2006'
        ])
    end_date = forms.DateField(input_formats=[
        '%d.%m.%Y',       # '25.10.2006'
        ])


class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = '__all__'
        labels = {
            'name':'Imię',
            'surname':'Nazwisko',
        }

templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<!-- Home Page -->

<div data-role="page" id="home">

    {% include "app/include/header.html" %}

    <div data-role="main" class="ui-content">
        <a href="#semesters" class="ui-btn ui-corner-all ui-shadow">Zarządzanie semestrami</a>
        <a href="#students" class="ui-btn ui-corner-all ui-shadow">Baza studentów</a>
    </div>

    {% include "app/include/footer.html" %}

</div>

<!-- / Home Page -->

<!-- Semester's Index Page -->

<div data-role="page" id="semesters">
    {% include "app/include/header.html" %}
    <div data-role="main" class="ui-content" id="semesters-main"></div>
    {% include "app/include/footer.html" %}
</div>

<!-- / Semester's Index Page -->

<!-- Semester's Creating Dialog Page -->

<div data-role="page" data-dialog="true" id="new-semester">

    <div data-role="header">
        <h1>Dodaj semestr</h1>
    </div>

    <div data-role="main" class="ui-content" id="new-semester-main">
        <div id="sem-result-box"></div>
        <form action="" method="post" id="new-semester-form">
            {% csrf_token %}
            <div class="ui-field-contain">
                <label for="id_academic_year">Rok akademicki:</label>
                <input id="id_academic_year" maxlength="7" name="academic_year" type="text" placeholder="np. 2010/11">
            </div>
            <div class="ui-field-contain">
                <fieldset data-role="controlgroup" data-type="horizontal">
                    <legend>Semestr:</legend>
                    <label for="id_sem_type_0">zimowy</label>
                    <input type="radio" name="sem_type" id="id_sem_type_0" value="z" checked>
                    <label for="id_sem_type_1">letni</label>
                    <input type="radio" name="sem_type" id="id_sem_type_1" value="l">
                </fieldset>
            </div>
            <div class="ui-field-contain">
                <label for="id_start_date">Data rozpoczęcia:</label>
                <input id="id_start_date" name="start_date" type="date">
            </div>
            <div class="ui-field-contain">
                <label for="id_end_date">Data zakończenia:</label>
                <input id="id_end_date" name="end_date" type="date">
            </div>
            <input type="submit" value="Dodaj">
        </form>
    </div>

</div>

<!-- / Semester's Creating Dialog Page -->

<!-- Semester's properties Dialog Page -->

<div data-role="page" data-dialog="true" id="sem-properties">

    <div data-role="header">
        <h1>Opcje semestru</h1>
    </div>

    <div data-role="main" class="ui-content" id="sem-properties-main"></div>
</div>

<!-- / Semester's properties Dialog Page -->

<!-- Student's Index Page -->

<div data-role="page" id="students">
    {% include "app/include/header.html" %}
    <div data-role="main" class="ui-content" id="students-main"></div>
    {% include "app/include/footer.html" %}
</div>

<!-- / Student's Index Page -->

<!-- Student's Details Page -->

<div data-role="page" id="student-details">
    {% include "app/include/header.html" %}
    <div data-role="main" class="ui-content" id="student-details-main"></div>
    {% include "app/include/footer.html" %}
</div>

<!-- / Student's Details Page -->

<!-- Student's Creating Dialog Page -->

<div data-role="page" data-dialog="true" id="new-student">

    <div data-role="header">
        <h1>Dodaj studenta</h1>
    </div>

    <div data-role="main" class="ui-content" id="new-student-main">
        <div id="std-result-box"></div>
        <form action="" method="post" id="new-student-form">
            {% csrf_token %}
            <div class="ui-field-contain">
                <label for="id_name">Imię:</label>
                <input id="id_name" name="name" type="text">
            </div>
            <div class="ui-field-contain">
                <label for="id_surname">Nazwisko:</label>
                <input id="id_surname" name="surname" type="text">
            </div>
            <input type="submit" value="Dodaj">
        </form>
    </div>

    <script>

    </script>

</div>

<!-- / Student's Creating Dialog Page -->

{% endblock content %}

templates/app/layout.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Praca Magisterska</title>
<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css" />
<link rel="stylesheet" href="{% static 'css/site.css' %}?v={% now "U" %}">
<script src="http://code.jquery.com/jquery-1.12.4.min.js"></script>
<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
<script src="{% static 'scripts/main.js' %}?v={% now "U" %}"></script>
<script src="{% static 'scripts/semesters.js' %}?v={% now "U" %}"></script>
<script src="{% static 'scripts/students.js' %}?v={% now "U" %}"></script>
</head>
<body>{% block content %}{% endblock %}</body>
</html>